In [1]:
import pandas as pd
import datetime
import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import numpy as np
from matplotlib import pyplot as plt

In [8]:
fund=pd.read_csv("fund.csv")
complexity=pd.read_csv("complexity.csv")
complexity['Year']=complexity['Date']
dfmerge = pd.merge(fund, complexity, on=['Year', 'Ticker'])
dfmerge = dfmerge.dropna(subset=['Year', 'Ticker','TDTA', 'AP_TOV', 'Inv_TOV', 'ol', 'AR_TOV', 'ROA', 'CFM','btm','GPM','Beta'])
dfmerge.reset_index(drop=True, inplace=True)
dfmerge

,tic,ap,at,bkvlps,cogs,ebitda,gp,invt,lt,oancf,...,venture,ventures,warranty,warranties,worldwide,filename,Company Name,Date,Ticker Symbol,Sum
0,AAPL,22367.0,207000.0,137.3968,99849.0,55756.0,71061.0,1764.0,83451.0,53666.0,...,0,1,34,4,10,2013_Apple.pdf,Apple,2013,AAPL,862
1,AAPL,30196.0,231839.0,19.0153,104312.0,60449.0,78483.0,2111.0,120292.0,59713.0,...,0,1,32,4,10,2014_Apple.pdf,Apple,2014,AAPL,920
2,AAPL,35490.0,290479.0,21.3946,129589.0,81730.0,104126.0,2349.0,171124.0,81266.0,...,0,1,24,3,9,2015_Apple.pdf,Apple,2015,AAPL,868
3,AAPL,37294.0,321686.0,24.0339,121576.0,69276.0,93515.0,2132.0,193437.0,65824.0,...,0,1,24,3,9,2016_Apple.pdf,Apple,2016,AAPL,863
4,AAPL,46236.0,338516.0,20.3653,150482.0,75230.0,109692.0,4106.0,248028.0,69391.0,...,0,1,13,3,3,2019_Apple.pdf,Apple,2019,AAPL,727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,WMT,37415.0,204751.0,23.5865,349199.0,34140.0,125060.0,44858.0,121921.0,23257.0,...,1,2,0,0,1,2014_Walmart.pdf,Walmart,2014,WMT,312
193,WMT,41433.0,198825.0,25.5243,351176.0,29594.0,130978.0,43046.0,118290.0,31530.0,...,1,0,0,0,3,2017_Walmart.pdf,Walmart,2017,WMT,960
194,WMT,46092.0,204522.0,26.3784,362867.0,29182.0,133918.0,43783.0,123700.0,28337.0,...,1,1,0,0,3,2018_Walmart.pdf,Walmart,2018,WMT,1027
195,WMT,47060.0,219295.0,25.1897,374623.0,30149.0,137106.0,44269.0,139661.0,27753.0,...,1,1,0,0,4,2019_Walmart.pdf,Walmart,2019,WMT,1088
196,WMT,46973.0,236495.0,26.3616,383618.0,30139.0,137808.0,44435.0,154943.0,25255.0,...,1,1,0,0,4,2020_Walmart.pdf,Walmart,2020,WMT,1023